[project]
name = "moasteroids"
version = "0.1.0"
description = "Build Asteroids using Python and Pygame - boot.dev project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygame==2.6.1",
]
